### Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.

In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns 
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.metrics import r2_score, accuracy_score, recall_score, precision_score, classification_report, confusion_matrix
from sklearn.datasets import load_iris

In [10]:
data = load_iris()
data.items()

dict_items([('data', array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])), ('target', array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])), ('frame', None), ('target_names', array(['setosa', 'versicolor', 'virginica'], dtype='<U10')), ('DESCR', '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n|details-start|\n**References**\n|details-split|\n\n- Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n  Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n  Mathematical Statistics" (John Wiley, NY, 1950).\n- Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n  (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n- Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n  Structure and Classification Rule for Recognition in Partially Exposed\n  Environments".  IEEE Transactions on Pattern Analysis and Machine\n  Intelligence, Vol. PAMI-2, No. 1, 67-71.\n- Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n  on Information Theory, May 1972, 431-433.\n- See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n  conceptual clustering system finds 3 classes in the data.\n- Many, many more ...\n\n|details-end|\n'), ('feature_names', ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']), ('filename', 'iris.csv'), ('data_module', 'sklearn.datasets.data')])

In [12]:
data.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n|details-start|\n**References**\n|details-split|\n\n- Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n  Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n  Mathematical Statistics" (John Wiley, NY, 1950).\n- Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n  (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n- Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n  Structure and Classification Rule for Recognition in Partially Exposed\n  Environments".  IEEE Transactions on Pattern Analysis and Machine\n  Intelligence, Vol. PAMI-2, No. 1, 67-71.\n- Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n  on Information Theory, May 1972, 431-433.\n- See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n  conceptual clustering system finds 3 classes in the data.\n- Many, many more ...\n\n|details-end|\n'

In [13]:
df = pd.DataFrame(data.data, columns= data.feature_names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [15]:
y = data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [17]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.20, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [20]:
model = KNeighborsClassifier(n_neighbors=5,weights="uniform")
model

KNeighborsClassifier()

In [21]:
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
accuracy_score_model = accuracy_score(y_test, y_predict)
print(f"the test accuracy of the model is : {accuracy_score_model}")

the test accuracy of the model is : 1.0

In [22]:
y_predict_train = model.predict(X_train)
accuracy_score_model_traindata = accuracy_score(y_train, y_predict_train)
print(f"the test accuracy of the model is : {accuracy_score_model_traindata}")

the test accuracy of the model is : 0.9666666666666667

### Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.

In [65]:
data = pd.read_csv(r"C:\Users\dhruv\Documents\ML\datasets\boston.csv")
data

     Unnamed: 0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO       B  LSTAT  Price
0             0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0     15.3  396.90   4.98   24.0
1             1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0     17.8  396.90   9.14   21.6
2             2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0     17.8  392.83   4.03   34.7
3             3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0     18.7  394.63   2.94   33.4
4             4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0     18.7  396.90   5.33   36.2
..          ...      ...   ...    ...   ...    ...    ...   ...     ...  ...    ...      ...     ...    ...    ...
501         501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0     21.0  391.99   9.67   22.4
502         502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0     21.0  396.90   9.08   20.6
503         503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0     21.0  396.90   5.64   23.9
504         504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0     21.0  393.45   6.48   22.0
505         505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0     21.0  396.90   7.88   11.9

[506 rows x 15 columns]

In [66]:
data.drop("Unnamed: 0",axis=1,inplace=True)
data.head(3)

      CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO       B  LSTAT  Price
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0     17.8  392.83   4.03   34.7

In [67]:
data.corr()

             CRIM        ZN     INDUS      CHAS       NOX  ...       TAX   PTRATIO         B     LSTAT     Price
CRIM     1.000000 -0.200469  0.406583 -0.055892  0.420972  ...  0.582764  0.289946 -0.385064  0.455621 -0.388305
ZN      -0.200469  1.000000 -0.533828 -0.042697 -0.516604  ... -0.314563 -0.391679  0.175520 -0.412995  0.360445
INDUS    0.406583 -0.533828  1.000000  0.062938  0.763651  ...  0.720760  0.383248 -0.356977  0.603800 -0.483725
CHAS    -0.055892 -0.042697  0.062938  1.000000  0.091203  ... -0.035587 -0.121515  0.048788 -0.053929  0.175260
NOX      0.420972 -0.516604  0.763651  0.091203  1.000000  ...  0.668023  0.188933 -0.380051  0.590879 -0.427321
RM      -0.219247  0.311991 -0.391676  0.091251 -0.302188  ... -0.292048 -0.355501  0.128069 -0.613808  0.695360
AGE      0.352734 -0.569537  0.644779  0.086518  0.731470  ...  0.506456  0.261515 -0.273534  0.602339 -0.376955
DIS     -0.379670  0.664408 -0.708027 -0.099176 -0.769230  ... -0.534432 -0.232471  0.291512 -0.496996  0.249929
RAD      0.625505 -0.311948  0.595129 -0.007368  0.611441  ...  0.910228  0.464741 -0.444413  0.488676 -0.381626
TAX      0.582764 -0.314563  0.720760 -0.035587  0.668023  ...  1.000000  0.460853 -0.441808  0.543993 -0.468536
PTRATIO  0.289946 -0.391679  0.383248 -0.121515  0.188933  ...  0.460853  1.000000 -0.177383  0.374044 -0.507787
B       -0.385064  0.175520 -0.356977  0.048788 -0.380051  ... -0.441808 -0.177383  1.000000 -0.366087  0.333461
LSTAT    0.455621 -0.412995  0.603800 -0.053929  0.590879  ...  0.543993  0.374044 -0.366087  1.000000 -0.737663
Price   -0.388305  0.360445 -0.483725  0.175260 -0.427321  ... -0.468536 -0.507787  0.333461 -0.737663  1.000000

[14 rows x 14 columns]

In [68]:
data.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
Price      0
dtype: int64

In [69]:
data.duplicated().sum()

0

In [70]:
data.head(3)

      CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO       B  LSTAT  Price
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0     17.8  392.83   4.03   34.7

In [71]:
X_train, X_test, y_train, y_test = train_test_split(data.drop("Price",axis=1), data.Price, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((404, 13), (102, 13), (404,), (102,))

In [72]:
X_train.head(3)

         CRIM    ZN  INDUS  CHAS     NOX     RM   AGE     DIS   RAD    TAX  PTRATIO       B  LSTAT
477  15.02340   0.0  18.10   0.0  0.6140  5.304  97.3  2.1007  24.0  666.0     20.2  349.48  24.91
15    0.62739   0.0   8.14   0.0  0.5380  5.834  56.5  4.4986   4.0  307.0     21.0  395.62   8.47
332   0.03466  35.0   6.06   0.0  0.4379  6.031  23.3  6.6407   1.0  304.0     16.9  362.25   7.83

In [73]:
model = KNeighborsRegressor(n_neighbors=5, weights='uniform')
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
accuracy = r2_score(y_test, y_predict)
print(f"the test accuracy of the model is : {accuracy}")
y_predict_train = model.predict(X_train)
accuracy_train = r2_score(y_train, y_predict_train)
print(f"the train accuracy of the model is : {accuracy_train}")

the test accuracy of the model is : 0.6473640882039258
the train accuracy of the model is : 0.6839203981935851

In [74]:
model = KNeighborsRegressor(n_neighbors=10, weights='distance')
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
accuracy = r2_score(y_test, y_predict)
print(f"the test accuracy of the model is : {accuracy}")
y_predict_train = model.predict(X_train)
accuracy_train = r2_score(y_train, y_predict_train)
print(f"the train accuracy of the model is : {accuracy_train}")

the test accuracy of the model is : 0.5646848993861198
the train accuracy of the model is : 1.0

In [75]:
model = KNeighborsRegressor(n_neighbors=10, weights='uniform')
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
accuracy = r2_score(y_test, y_predict)
print(f"the test accuracy of the model is : {accuracy}")
y_predict_train = model.predict(X_train)
accuracy_train = r2_score(y_train, y_predict_train)
print(f"the train accuracy of the model is : {accuracy_train}")

the test accuracy of the model is : 0.5038055971345883
the train accuracy of the model is : 0.582564299906513

## Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.

In [76]:
X_train.head(3)

         CRIM    ZN  INDUS  CHAS     NOX     RM   AGE     DIS   RAD    TAX  PTRATIO       B  LSTAT
477  15.02340   0.0  18.10   0.0  0.6140  5.304  97.3  2.1007  24.0  666.0     20.2  349.48  24.91
15    0.62739   0.0   8.14   0.0  0.5380  5.834  56.5  4.4986   4.0  307.0     21.0  395.62   8.47
332   0.03466  35.0   6.06   0.0  0.4379  6.031  23.3  6.6407   1.0  304.0     16.9  362.25   7.83

In [44]:
X_test.head(3)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO       B  LSTAT
173  0.09178   0.0   4.05   0.0  0.510  6.416  84.1  2.6463  5.0  296.0     16.6  395.50   9.04
274  0.05644  40.0   6.41   1.0  0.447  6.758  32.9  4.0776  4.0  254.0     17.6  396.90   3.53
491  0.10574   0.0  27.74   0.0  0.609  5.983  98.8  1.8681  4.0  711.0     20.1  390.11  18.07

In [45]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [46]:
preprocessor = StandardScaler()

In [47]:
preprocessor.fit(X_train)

StandardScaler()

In [49]:
X_train = preprocessor.transform(X_train)
X_test = preprocessor.transform(X_test)

In [50]:
X_test

array([[-0.39680933, -0.50032012, -1.00711147, ..., -0.77195078,
         0.42887165, -0.48121032],
       [-0.40079621,  1.2294987 , -0.66439105, ..., -0.32270256,
         0.44418004, -1.25709448],
       [-0.39523443, -0.50032012,  2.43316256, ...,  0.80041799,
         0.36993437,  0.79033849],
       ...,
       [ 1.1779666 , -0.50032012,  1.03323679, ...,  0.84534281,
        -3.5124912 ,  1.23390203],
       [-0.40131065, -0.50032012, -0.94321444, ...,  0.08162084,
         0.43422959,  0.05669848],
       [-0.39643252, -0.50032012,  0.26792466, ...,  0.17147048,
         0.29470458, -0.49529171]])

In [51]:
X_test

array([[-0.39680933, -0.50032012, -1.00711147, ..., -0.77195078,
         0.42887165, -0.48121032],
       [-0.40079621,  1.2294987 , -0.66439105, ..., -0.32270256,
         0.44418004, -1.25709448],
       [-0.39523443, -0.50032012,  2.43316256, ...,  0.80041799,
         0.36993437,  0.79033849],
       ...,
       [ 1.1779666 , -0.50032012,  1.03323679, ...,  0.84534281,
        -3.5124912 ,  1.23390203],
       [-0.40131065, -0.50032012, -0.94321444, ...,  0.08162084,
         0.43422959,  0.05669848],
       [-0.39643252, -0.50032012,  0.26792466, ...,  0.17147048,
         0.29470458, -0.49529171]])

In [52]:
y_train

477    12.0
15     19.9
332    19.4
423    13.4
19     18.2
       ...
106    19.5
270    21.1
348    24.5
435    13.4
102    18.6
Name: Price, Length: 404, dtype: float64

In [53]:
model = KNeighborsRegressor(n_neighbors=10, weights='uniform')
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
accuracy = r2_score(y_test, y_predict)
print(f"the test accuracy of the model is : {accuracy}")
y_predict_train = model.predict(X_train)
accuracy_train = r2_score(y_train, y_predict_train)
print(f"the train accuracy of the model is : {accuracy_train}")

the test accuracy of the model is : 0.6613535344781623
the train accuracy of the model is : 0.7723590428204482

In [54]:
model = KNeighborsRegressor(n_neighbors=10, weights='distance')
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
accuracy = r2_score(y_test, y_predict)
print(f"the test accuracy of the model is : {accuracy}")
y_predict_train = model.predict(X_train)
accuracy_train = r2_score(y_train, y_predict_train)
print(f"the train accuracy of the model is : {accuracy_train}")

the test accuracy of the model is : 0.6914700774412903
the train accuracy of the model is : 1.0

In [ ]:
### to get the more test accuracy we can use cross validation methods

## Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

In [58]:
data = load_iris()
df = pd.DataFrame(data.data, columns= data.feature_names)
y = data.target
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.20, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
model = KNeighborsClassifier()
params = {
    
    "n_neighbors" :[1,2,3,4,5],
    "weights" : ["uniform", "distance"],
    "algorithm" : ["auto", "ball_tree", "kd_tree"]
    
}
grid_model = GridSearchCV(model, param_grid=params, cv=5, verbose=1, scoring="accuracy")
grid_model

(120, 4) (30, 4) (120,) (30,)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree'],
                         'n_neighbors': [1, 2, 3, 4, 5],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy', verbose=1)

In [59]:
grid_model.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree'],
                         'n_neighbors': [1, 2, 3, 4, 5],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy', verbose=1)

In [60]:
grid_model.best_estimator_

KNeighborsClassifier(n_neighbors=3)

In [61]:
## we can see the best model we can get at k = 3

In [89]:
data = load_iris()
df = pd.DataFrame(data.data, columns= data.feature_names)
y = data.target
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.20, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train,y_train)
y_pre = model.predict(X_test)
y_pre_train = model.predict(X_train)
accuracy_train = accuracy_score(y_train, y_pre_train)
accuracy_test = accuracy_score(y_test, y_pre)

print(f"the train score of the model is {accuracy_train}")
print(f"the test score of the model is {accuracy_test}")

(120, 4) (30, 4) (120,) (30,)
the train score of the model is 0.95
the test score of the model is 1.0

#### Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.

In [84]:
model = KNeighborsClassifier(n_neighbors=3, weights="distance")
model.fit(X_train,y_train)
y_pre = model.predict(X_test)
y_pre_train = model.predict(X_train)
accuracy_train = accuracy_score(y_train, y_pre_train)
accuracy_test = accuracy_score(y_test, y_pre)

print(f"the train score of the model is {accuracy_train}")
print(f"the test score of the model is {accuracy_test}")

the train score of the model is 1.0
the test score of the model is 1.0

#### Q6. Implement a function to standardise the features before applying KNN classifier.

In [88]:
def stander_scaler(data):
    columns = data.columns

    for i in columns :
        data[i] = (data[i].mean() - data[i])/data[i].std()
    return data

In [90]:
data = load_iris()
df = pd.DataFrame(data.data, columns= data.feature_names)
y = data.target
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.20, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(120, 4) (30, 4) (120,) (30,)

In [91]:
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [92]:
X_train

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                 4.6               3.6                1.0               0.2
15                 5.7               4.4                1.5               0.4
65                 6.7               3.1                4.4               1.4
11                 4.8               3.4                1.6               0.2
42                 4.4               3.2                1.3               0.2
..                 ...               ...                ...               ...
71                 6.1               2.8                4.0               1.3
106                4.9               2.5                4.5               1.7
14                 5.8               4.0                1.2               0.2
92                 5.8               2.6                4.0               1.2
102                7.1               3.0                5.9               2.1

[120 rows x 4 columns]

In [93]:
X_train = stander_scaler(X_train)
X_train

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22            1.467783         -1.198632           1.556011          1.307122
15            0.132515         -2.979881           1.270679          1.041267
65           -1.081364         -0.085352          -0.384247         -0.288010
11            1.225007         -0.753320           1.213612          1.307122
42            1.710558         -0.308008           1.384811          1.307122
..                 ...               ...                ...               ...
71           -0.353037          0.582617          -0.155981         -0.155082
106           1.103619          1.250585          -0.441314         -0.686793
14            0.011127         -2.089257           1.441878          1.307122
92            0.011127          1.027929          -0.155981         -0.022155
102          -1.566916          0.137305          -1.240243         -1.218504

[120 rows x 4 columns]

In [94]:
X_test = stander_scaler(X_test)
X_test

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73           -0.142007          0.623850          -0.443526          0.078102
18            0.331351         -1.975526           1.185754          1.187966
118          -2.035440          1.143726          -1.638331         -1.278399
78           -0.023668          0.363913          -0.334907         -0.291853
76           -0.970384          0.623850          -0.497835         -0.168535
31            0.686369         -0.935775           1.294372          1.064648
64            0.449690          0.363913           0.153876         -0.045217
141          -1.088724         -0.155963          -0.660763         -1.278399
68           -0.260347          2.183476          -0.334907         -0.291853
82            0.213011          0.883788          -0.009052          0.078102
110          -0.615366         -0.415900          -0.660763         -0.908445
12            1.396407          0.103975           1.348682          1.434603
36            0.568030         -1.195713           1.402991          1.311284
9             1.278067         -0.155963           1.294372          1.434603
19            1.041388         -1.975526           1.294372          1.187966
56           -0.378687         -0.675838          -0.443526         -0.415172
104          -0.615366          0.103975          -1.040929         -1.155081
69            0.449690          1.403663          -0.009052          0.201420
55            0.331351          0.623850          -0.334907         -0.045217
132          -0.497026          0.623850          -0.932310         -1.155081
29            1.514746         -0.415900           1.240063          1.311284
127          -0.142007          0.103975          -0.552145         -0.661808
26            1.159728         -0.935775           1.240063          1.064648
128          -0.497026          0.623850          -0.932310         -1.031763
131          -2.272119         -1.975526          -1.366785         -0.908445
145          -0.852045          0.103975          -0.715073         -1.278399
108          -0.852045          1.403663          -1.040929         -0.661808
143          -0.970384         -0.415900          -1.095238         -1.278399
45            1.396407          0.103975           1.348682          1.187966
30            1.396407         -0.155963           1.240063          1.311284

In [95]:
model = KNeighborsClassifier(n_neighbors=3, weights="distance")
model.fit(X_train,y_train)
y_pre = model.predict(X_test)
y_pre_train = model.predict(X_train)
accuracy_train = accuracy_score(y_train, y_pre_train)
accuracy_test = accuracy_score(y_test, y_pre)

print(f"the train score of the model is {accuracy_train}")
print(f"the test score of the model is {accuracy_test}")

the train score of the model is 1.0
the test score of the model is 0.9666666666666667

#### Q7. Write a Python function to calculate the euclidean distance between two points.

In [96]:
def distance_euclidean(x,y):
    return np.sqrt((x-y)**2)

In [100]:
X_train.iloc[:,0]

22     1.467783
15     0.132515
65    -1.081364
11     1.225007
42     1.710558
         ...
71    -0.353037
106    1.103619
14     0.011127
92     0.011127
102   -1.566916
Name: sepal length (cm), Length: 120, dtype: float64

In [101]:
X_train.iloc[:,1]

22    -1.198632
15    -2.979881
65    -0.085352
11    -0.753320
42    -0.308008
         ...
71     0.582617
106    1.250585
14    -2.089257
92     1.027929
102    0.137305
Name: sepal width (cm), Length: 120, dtype: float64

In [102]:
distance_euclidean(X_train.iloc[:,0],X_train.iloc[:,1])

22     2.666415
15     3.112397
65     0.996013
11     1.978327
42     2.018566
         ...
71     0.935654
106    0.146967
14     2.100384
92     1.016802
102    1.704221
Length: 120, dtype: float64

#### Q8. Write a Python function to calculate the manhattan distance between two points

In [103]:
def distance_manhanttan(x,y):
    return np.abs(x-y)

In [104]:
distance_manhanttan(X_train.iloc[:,0],X_train.iloc[:,1])

22     2.666415
15     3.112397
65     0.996013
11     1.978327
42     2.018566
         ...
71     0.935654
106    0.146967
14     2.100384
92     1.016802
102    1.704221
Length: 120, dtype: float64